/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.graphicstore.product.avro.schema;
@org.apache.avro.specific.AvroGenerated
public enum category_enum implements org.apache.avro.generic.GenericEnumSymbol<category_enum> {
  DIGITAL, OFF_SET, SUBLIMACAO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"category_enum\",\"namespace\":\"com.graphicstore.product.avro.schema\",\"symbols\":[\"DIGITAL\",\"OFF_SET\",\"SUBLIMACAO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
