/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.graphicstore.product.avro.schema;
@org.apache.avro.specific.AvroGenerated
public enum color_enum implements org.apache.avro.generic.GenericEnumSymbol<color_enum> {
  _4x4, _4x1, _4x0, _1x0, _1x1, _1x4  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"color_enum\",\"namespace\":\"com.graphicstore.product.avro.schema\",\"symbols\":[\"_4x4\",\"_4x1\",\"_4x0\",\"_1x0\",\"_1x1\",\"_1x4\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
